import { Match, HighlightEvent } from '../types';

export const initialMatches: Match[] = [
  {
    id: 'm1',
    title: 'Academy League Final',
    sport: 'Football',
    homeTeam: 'Manchester Academy',
    awayTeam: 'Lions FC',
    venue: 'St. George Park Stadium',
    date: 'Today, 14:30',
    durationMinutes: 90,
    homeScore: 2,
    awayScore: 1,
    status: 'live',
    recordingSettings: {
      mode: 'OPTIMIZED_BUFFER',
      bufferBeforeSeconds: 20,
      bufferAfterSeconds: 20,
      quality: '1080p',
      autoUpload: true,
      gridOverlayEnabled: true,
      audioEnabled: true,
    },
    connectedDevicesCount: 3,
    highlightCount: 8,
    code: 'PV-8921',
  },
  {
    id: 'm2',
    title: 'U18 Regional Derby',
    sport: 'Football',
    homeTeam: 'Oakwood Rovers',
    awayTeam: 'Westside Athletic',
    venue: 'Oakwood Sports Complex',
    date: 'Yesterday, 16:00',
    durationMinutes: 90,
    homeScore: 0,
    awayScore: 0,
    status: 'completed',
    recordingSettings: {
      mode: 'FULL_MATCH',
      bufferBeforeSeconds: 30,
      bufferAfterSeconds: 30,
      quality: '1080p',
      autoUpload: false,
      gridOverlayEnabled: true,
      audioEnabled: true,
    },
    connectedDevicesCount: 2,
    highlightCount: 5,
    code: 'PV-3410',
  },
  {
    id: 'm3',
    title: 'University Cup Semi',
    sport: 'Football',
    homeTeam: 'Imperial College',
    awayTeam: 'UCL Strikers',
    venue: 'Kingston Arena',
    date: 'Aug 2, 2026',
    durationMinutes: 90,
    homeScore: 3,
    awayScore: 2,
    status: 'completed',
    recordingSettings: {
      mode: 'OPTIMIZED_BUFFER',
      bufferBeforeSeconds: 20,
      bufferAfterSeconds: 20,
      quality: '720p',
      autoUpload: true,
      gridOverlayEnabled: false,
      audioEnabled: true,
    },
    connectedDevicesCount: 4,
    highlightCount: 12,
    code: 'PV-1109',
  },
];

export const initialHighlights: HighlightEvent[] = [
  {
    id: 'h1',
    matchId: 'm1',
    type: 'Goal',
    timestamp: '42:15',
    timestampSeconds: 2535,
    tag: 'Disallowed Goal Review',
    cameraAngles: ['Main Stand', 'Behind North Goal', 'Tactical High View'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    decision: {
      id: 'd1',
      eventId: 'h1',
      verdict: 'Goal',
      refereeNotes: 'Ball completely crossed line before contact. Goal confirmed.',
      decidedAt: '14:48',
    },
  },
  {
    id: 'h2',
    matchId: 'm1',
    type: 'Possible Goal',
    timestamp: '68:40',
    timestampSeconds: 4120,
    tag: 'Goal Line Technology Check',
    cameraAngles: ['Behind Goal', 'Main Stand'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=500',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    decision: {
      id: 'd2',
      eventId: 'h2',
      verdict: 'No Goal',
      refereeNotes: 'Ball stayed on the line. Play on.',
      decidedAt: '15:15',
    },
  },
  {
    id: 'h3',
    matchId: 'm1',
    type: 'Red Card',
    timestamp: '78:10',
    timestampSeconds: 4690,
    tag: 'Serious Foul Play',
    cameraAngles: ['Main Stand', 'Left Touchline', 'Tactical High View'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=500',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    decision: {
      id: 'd3',
      eventId: 'h3',
      verdict: 'Red Card',
      refereeNotes: 'High studs challenge. Direct send-off upheld.',
      decidedAt: '15:26',
    },
  },
  {
    id: 'h4',
    matchId: 'm1',
    type: 'Offside',
    timestamp: '85:22',
    timestampSeconds: 5122,
    tag: 'VAR Offside Line Check',
    cameraAngles: ['Side Pitch Cam 1', 'Main Stand'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=500',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyplays.mp4',
  },
  {
    id: 'h5',
    matchId: 'm2',
    type: 'Penalty',
    timestamp: '33:05',
    timestampSeconds: 1985,
    tag: 'Box Tackle Review',
    cameraAngles: ['Behind Goal'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=500',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
  },
];
